<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="footer-container">
    <div class="footer">
        <?= $block->getChildHtml() ?>
        <p class="bugs"><?= $block->escapeHtml(__('teste')) ?> - <a
            href="http://www.magentocommerce.com/bug-tracking"
            target="_blank"><strong><?= $block->escapeHtml(__('teste')) ?></strong></a>
        </p>
        <address><?= $block->escapeHtml($block->getCopyright()) ?></address>
    </div>
</div>
